# .github/actions/azure_login/action.yml
name: 'Azure CLI Login'
description: 'A custom action to login to Azure CLI using a service principal.'
inputs:
  azure-client-id:
    description: 'Azure Client ID'
    required: true
  azure-client-secret:
    description: 'Azure Client Secret'
    required: true
  azure-tenant-id:
    description: 'Azure Tenant ID'
    required: true

runs:
  using: 'composite'  # Indicating that this is a composite action
  steps:
    - name: Set up Azure CLI
      run: |
        echo "Setting up Azure CLI"
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      shell: bash

    - name: Login to Azure
      run: |
        echo "Logging in to Azure using service principal"
        az login --service-principal -u ${{ inputs.azure-client-id }} -p ${{ inputs.azure-client-secret }} -t ${{ inputs.azure-tenant-id }}
      shell: bash
