name: 'Create custom Repository Dispatch'
description: 'Dispatch a repository event to trigger workflows in another repository.'
author: 'Tridib Bas'

inputs:
  repo_name:
    description: 'The repository to dispatch the event to (format: owner/repo).'
    required: true
  event_type:
    description: 'The type of event to trigger.'
    required: true
  token:
    description: 'GitHub token with repository permissions.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Install Python Dependencies
      run: pip install requests
      shell: bash
    
    - name: Run Python Script
      run: python3 dispatch.py
      shell: bash 
      env:
        INPUT_REPO_NAME: ${{ inputs.repo_name }}
        INPUT_EVENT_TYPE: ${{ inputs.event_type }}
        INPUT_TOKEN: ${{ inputs.token }}

branding:
  icon: 'zap'
  color: 'yellow'
