name: Docker Login, Pull, and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker Image
      run: docker pull ubuntu:latest

    - name: Run Docker Container
      run: docker run -d -p 8080:80 ubuntu:latest
