name: Docker Login, Pull, and Run Apache

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Apache Image
      run: docker pull httpd:latest

    - name: Run Apache Container
      run: docker run -d -p 8080:80 httpd:latest
