name: Docker Login, Pull, Run Apache, Display Container Info, and Curl

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Apache Image
      run: docker pull httpd:latest

    - name: Run Apache Container
      run: docker run -d -p 80:80 httpd:latest

    - name: Display Container Info
      run: docker ps -a

    - name: Wait for Apache to Start
      run: sleep 10  # Adjust the delay as needed

    - name: Curl localhost
      run: curl localhost

    - name: Display Apache Container Logs
      run: docker logs $(docker ps -q)

    
