name: Python Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker Image
        run: docker build -t python-hello .

      - name: Run Docker Container
        run: docker run -p 8080:80 python-hello
