name: Docker login, pull, and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Python Script
        run: python3 dock.py
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t image .

      - name: Show Docker Context
        run: ls -la

      - name: Show Docker Build Context
        run: ls -la $GITHUB_WORKSPACE

      - name: Docker Images
        run: docker images

      - name: Docker Run Container
        run: docker run --name my_life -itd -p 80:80 image

      - name: Docker Containers
        run: docker ps -a
