name: Simple Workflow with Input and Output

on:
  push:
    branches:
      - main

jobs:
  simple_job:
    runs-on: ubuntu-latest

    inputs:
      parameters:
        - name: greeting
          description: 'Greeting message'
          required: true
        - name: who-to-greet
          description: 'Name to greet'
          required: true

    outputs:
      id: greeting-output
      value:
        greeting: ${{ needs.simple_job.outputs.greeting }}
        who: ${{ needs.simple_job.outputs.who }}

    steps:
      - name: Set Greeting and Who
        id: set-greeting
        run: echo "::set-output name=greeting::${{ inputs.greeting }}::set-output name=who::${{ inputs.who-to-greet }}"

      - name: Show Greeting
        run: echo "Greeting: ${{ needs.simple_job.outputs.greeting }} to ${{ needs.simple_job.outputs.who }}"
