name: testing docker login 
on: 
  workflow_dispatch:

jobs:
  set-output:
    runs-on: ubuntu-latest
    outputs:
      docker-login: ${{ steps.docker.outputs.docker-login }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: set docker username 
        id: docker
        run: |
          echo "docker-login=$(echo ${{ secrets.DOCKER_USERNAME }} | base64)" >> $GITHUB_ENV


  user-outputs:
    runs-on: ubuntu-latest
    needs: set-output
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: docker login 
        run: |
          echo ${{ env.docker-login }} | base64 --decode | docker login -u ${{ needs.set-output.outputs.docker-login }} -p ${{ secrets.DOCKER_PASSWORD}}  
