name: Docker login , pull and Run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: alpine-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
#        with:
#          ref: master

      - name: Run python script
        run: python3 dock.py
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Pull
        run: docker pull ubuntu

      - name: Docker images
        run: docker images

      - name: docker run container
        run: docker run  --name  my_life -itd  -p 80:80 ubuntu

      - name: docker containers
        run: docker ps -a




