name: Docker Build

on:
  workflow_dispatch:
    inputs:
      username:      
        description: 'Docker Hub username'
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: ./.github/actions/docker-login@v2
      with:
        username: ${{ github.event.inputs.username }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t {{ inputs.username }}/yourimage:latest .
        docker push {{ inputs.username }}/yourimage:latest
