name: "Docker Simple"

on: [push]

jobs:
  docker_simple:
    runs-on: ubuntu-latest
    name: "A Simple Docker Action"
    steps:
      - name: "Greet & Output Time"
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'

      - name: "Get the output time"
        run: echo "The time was ${{ steps.hello.outputs.time }}"
