name: mintu

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Python Script
        run: |
          pip install requests 
          python3 dock.py
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: delete docker images 
      #   run: docker rmi $(docker images -qa)

      - name: Docker Build
        run: docker build -t image .

      - name: Show Docker Build Context
        run: ls -lrth  $GITHUB_WORKSPACE

      - name: Docker Images
        run: docker images

      - name: Docker Run Container
        run: docker run --name my_life -itd -p 8080:80 image

      - name: Docker Containers
        run: docker ps -a
      - name: helm version 
        run: helm version 
