name: Docker Build and Run

on: [workflow_call]
  # push:
  #   branches:
  #     - main
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Maxwell134/test
          path: test
          ref: master

      - name: Check OS
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "Running on Linux"
            cat /etc/os-release
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "Running on Windows"
            systeminfo | find "OS Name"
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "Running on macOS"
            sw_vers -productVersion
          else
            echo "Unknown operating system"
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Check Python version
        run: python -V

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt

      - name: Build Docker image
        run: docker build -t myflaskapp test/

      - name: Run Docker container
        run: docker run -itd -p 80:80 myflaskapp

      - name: Wait for the Flask app to start
        run: sleep 5

      - name: Docker containers
        run: docker ps -a

      - name: Test the running container
        run: curl http://localhost:80

      - name: Wait for the Flask app to start
        run: sleep 10
