name: Use Hello Action Workflow

on:
  push:
    branches:
      - main

jobs:
  use-hello-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RepoB
        uses: actions/checkout@v2

      - name: Use Hello Action from RepoA
        uses: actions/hello-world-docker-action@main
        with:
          who-to-greet: ${{ secrets.NAME }}

      - name: Print Time
        run: echo "Time: ${{ steps.hello.outputs.time }}"
