name: Use Basic Validation Action

on:
  push:
    branches:
      - main

jobs:
  use_basic_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Basic Validation Workflow
        uses: actions/Docker_login_actions/.github/workflows/main.yml@main

      # - name: Use Hello World Action
      #   uses: actions/Docker_login_actions/.github/workflows/main.yml@main
        
      - name: published
        run: echo "published"
