# .github/workflows/main.yml
name: Show Python Version

on:
  push:
    branches:
      - main

jobs:
  show-python-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: Maxwell134/Docker_login_actions@main
      with:
        python-version: '3.9'
