name: Example Workflow

on:
  workflow_dispatch

jobs:
   install:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python 3.12
        uses: Maxwell134/Docker_login_actions@main


      - name: Show Python Version
        run: python3.12 --version
