name: Example Workflow

on:
  workflow_dispatch

jobs:
  install:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker version
        run: |
          echo "Checking Docker version..."
          docker --version || echo "Docker is not installed." 

      # - name: Docker images
      #   run: docker images 

      - name: Run Azure CLI
        uses: ./.github/actions/azure_login 
        with:
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Check the Azure Account
        run: |
          echo "Checking the Azure account..."
          az account list -o table

      - name: Azure Logout
        run: |
          echo "Logging out of Azure..."
          az logout
