# .github/workflows/display-greeting.yml
name: Display Greeting

on:
  push:
    branches:
      - main

jobs:
  display-greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test My Name Action
        id: test-my-name2
        uses: Maxwell134/test321@main
        with:
          name: 'John'  # Replace with your desired name
