name: Use Docker Login Action

on:
  push:
    branches:
      - main

jobs:
  use_docker_login_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Docker Login Action
        uses: actions/Docker_login_actions/action.yaml@main
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t my-docker-image .
          docker push my-docker-image
