name: Use Hello Action Workflow

on:
  workflow_dispatch:
    inputs:
      myName:
        description: 'Name for the greeting'

jobs:
  use-hello-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Simple Hello Action from RepoA
        uses: .github/actions/sample_test/action.yml@main
        with:
          myName: ${{ github.event.inputs.myName }}
