name: Example Workflow

on:
  workflow_dispatch

jobs:
   install:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run azure cli 
        uses: ./.github/actions/azure_login 
        with:
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          
      - name: Check the Azure Account
        run: |
          echo "Checking the Azure account..."
          az account list -o table

      - name: az logout
        run: |
          az logout
    

