name: Example Workflow

on:
  workflow_dispatch

jobs:
   install:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run azure cli 
        uses: Maxwell134/azure_login@main
        with:
          azure-client-id: ${{ secrets.azure-client-id }}
          azure-client-secret: ${{ secrets.azure-client-secret }}
          azure-tenant-id: ${{ secrets.azure-tenant-id }}

