name: Use Hello Action Workflow

on:
  workflow_dispatch:
    inputs:
      myName:
        description: 'Name for the greeting'

jobs:
  use-hello-action-job:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Use Simple Hello Action from RepoA
        uses: Maxwell134/Docker_login_actions@main
        with:
          myName: ${{ github.event.inputs.myName }}
