# .github/workflows/use-test-action.yml
name: Use Test Action

on:
  push:
    branches:
      - main

jobs:
  use-test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Test Action
        id: test-action
        run: .github/actions/test-action/entrypoint.sh ${{ github.event.inputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
