name: Checking Docker Login

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: Maxwell134/Hello_world/.github/actions/docker-login@v1.0.0
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check Docker Build Condition
        id: check_condition
        run: |
          python3 docker_image_handler.py
        shell: bash

      - name: Display Build Status
        run: |
          echo "Build Status: ${{ env.build_status }}"
          

      - name: Docker Build
        if: ${{ env.build_status == 'proceed' }}
        run: |
          echo "Proceeding with Docker build..."
          docker build -t apache .


      - name: Upload a Build Artifact
        if: ${{ env.build_status == 'proceed' }}
        uses: actions/upload-artifact@v4.3.6
        with:
          name: docker-image
          path: apache.tar.gz
          if-no-files-found: warn
          compression-level: 6
          overwrite: false

      - name: Docker Images
        if: ${{ env.build_status == 'proceed' }}
        run: |
          echo "Proceeding with Docker run..."
          docker images
          docker run -itd --name my_image -p 8080:80 apache
          sleep 5
          curl localhost:8080
