name: Checking Docker Login

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: Maxwell134/Hello_world/.github/actions/docker-login@v1.0.0
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check Docker Build Condition
        id: check_condition
        run: |
          python3 docker_image_handler.py
        shell: bash

      - name: Display Build Status
        run: |
          echo "Build Status: ${{ env.build_status }}"
          

      - name: Docker Build
        if: ${{ env.build_status == 'proceed' }}
        run: |
          echo "Proceeding with Docker build..."
          docker build -t apache .

      - name: Save Docker Image to File
        run: |
          docker save apache | gzip > apache.tar.gz

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: apache.tar.gz

      - name: Docker Images
        if: ${{ env.build_status == 'proceed' }}
        run: |
          echo "Proceeding with Docker run..."
          docker images
          docker run -itd --name my_image -p 8080:80 apache
          sleep 5
          curl localhost:8080


      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
        if: ${{ env.build_status == 'skip' }}

      - name: List all files
        run: |
          ls -lrth 
          ls -lrth | grep apache.tar.gz


      # - name: Load Docker Image from File
      #   run: |
      #     gunzip -c /home/runner/work/Hello_world/Hello_world/docker-image/apache.tar.gz | docker load
      #     docker images
      #   if: ${{ env.build_status == 'skip' }}

      # - name: Run Docker Container
      #   run: |
      #     docker run -itd --name my_image -p 8080:80 apache
      #     sleep 5
      #     curl localhost:8080
        # if: ${{ env.build_status == 'skip' }}
