name: Checking Docker Login

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name'
        required: true
        default: 'nginx:latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: Maxwell134/Hello_world/.github/actions/docker-login@v1.0.0
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Pull Image
        run: |
          python3 docker_image_handler.py
        env:
          IMAGE_NAME: ${{ github.event.inputs.image_name }}

      - name: List Docker Images
        run: |
          docker images
