name: Checking docker login

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to docker
        uses: Maxwell134/Hello_world/.github/actions/docker-login@v1.0.0
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check Docker Build Condition
        id: check_condition
        run: |
          build_status=$(python3 docker_image_handler.py)
          echo 'Build status: ${build_status}'


      - name: Docker build
        if: ${{ env.build_status == 'proceed' }}
        run: |
          docker ps -a 

      - name: Docker Images
        if: ${{ env.build_status == 'proceed' }}
        run: |
          docker images 

        
        
