name: Build and Push Docker Image

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker and Log in
      uses: ./.github/actions/docker_login
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/your-image-name:latest .

    - name: Push Docker image
      run: docker push your-dockerhub-username/your-image-name:latest
