name: Checking docker login

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to docker
        uses: Maxwell134/Hello_world/.github/actions/docker-login@v1.0.0
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check Docker Build Condition
        id: check_condition
        run: |   
          result=$(python3 docker_image_handler.py)
          # Set the output for this step
          echo "::set-output name=build_status::$result"
        shell: bash
          

      - name: Display Build Status
        run: |
          echo "Build Status: ${{ steps.check_condition.outputs.build_status }}"

      - name: Docker build
        if: ${{ steps.check_condition.outputs.build_status == 'proceed' }}
        run: |
          echo "Proceeding with Docker build..."
          docker build -t apache .
        env:
          build_status: ${{ env.build_status }}

      - name: Docker Images
        if: ${{ steps.check_condition.outputs.build_status == 'proceed' }}
        run: |
          echo "Proceeding with Docker run..."
          docker images
          docker run -itd --name my_image -p 8080:80 apache
          sleep 5
          curl localhost:8080
        env:
          build_status: ${{ env.build_status }}

        
        
