name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image to pull'
        default: 'alpine:latest'
        required: true
        type: string

jobs:
  pull-and-run-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker Image
        run: docker pull ${{ inputs.image }}

      - name: Show Docker Images
        run: docker images

      - name: Run Docker Container
        run: docker run -itd --name my-container -p 80:80 ${{ inputs.image }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag ${{ inputs.image }} ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image }}

      - name: Push Docker Image to Main
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image }}
