name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image to pull'
        default: 'alpine:latest'
        required: true
        type: string

jobs:
  pull-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker Image
        run: docker pull ${{ inputs.image }}
