name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image to pull'
        default: 'alpine:latest'
        required: true
        type: string

jobs:
  pull-and-run-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker Image
        run: docker pull ${{ inputs.image }}

      - name: Show Docker Images
        run: docker images

      - name: Run Docker Container
        run: docker run -itd --name my-container -p 80:80 ${{ inputs.image }}
