name: Python Workflow with Output

on:
  workflow_dispatch
  

jobs:
  generate_data:
    runs-on: ubuntu-latest

    outputs:
      generated-data: ${{ steps.generate.outputs.generated-data }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Data
        id: generate
        run: |
          output=$(python3 main.py)
          echo "::set-output name=generated-data::$output"

  display_data:
    runs-on: ubuntu-latest
    needs: generate_data

    steps:
      - name: Display Data
        run: |
          generated_data="${{ needs.generate_data.outputs.generated-data }}"
          echo "Generated Data: $generated_data"
