name: Python Workflow with Output

on:
  push:
    branches:
      - main

jobs:
  generate_data:
    runs-on: ubuntu-latest

    outputs:
      generated-data: ${{ steps.generate.outputs.generated-data }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Data
        id: generate
        run: |
          python3 main.py > generated_data.txt
          echo "::set-output name=generated-data::generated_data.txt"

  display_data:
    runs-on: ubuntu-latest
    needs: generate_data

    steps:
      - name: Display Data
        run: |
          generated_data=$(cat ${{ needs.generate_data.outputs.generated-data }})
          echo "Generated Data: $generated_data"
