name: "docker login"

on:
  workflow_dispatch

jobs:
  docker-login:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "pypy-3.9"]

    steps:
      - name: checkout stage
        using: action/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

    - name: Run python
      run: python3 main.py

      

