name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y sshpass

    - name: Deploy to PythonAnywhere
      env:
        PA_USERNAME: Maxwell345
        PA_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_SSH_KEY: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}
      run: |
        # Save the private key from secrets
        echo "$PA_SSH_KEY" > private_key
        chmod 600 private_key

        # Upload code to PythonAnywhere using scp
        sshpass -p ${{ secrets.PYTHONANYWHERE_PASSWORD }} scp -o StrictHostKeyChecking=no -i private_key -r * $PA_USERNAME@ssh.pythonanywhere.com:/home/$PA_USERNAME/your_project_directory/

        # Define the URL for the PythonAnywhere API
        API_URL="https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/"

        # Reload the specific web app
        WEB_APP_NAME="<your-web-app-name>.pythonanywhere.com"
        curl -X POST -H "Authorization: Token $PA_API_TOKEN" "${API_URL}${WEB_APP_NAME}/reload/"

        echo "Deployment complete!"
