name: Cleanup Old Workflow Runs

on:
 workflow_dispatch  # Runs on the 1st of every month

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Run Cleanup Script
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          THRESHOLD_DATE=$(date -d "-4 months" +%Y-%m-%dT%H:%M:%SZ)
          echo "Deleting workflow runs older than $THRESHOLD_DATE from $REPO"
          
          WORKFLOW_RUNS=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs?per_page=100" | jq -c ".workflow_runs[] | select(.created_at < \"${THRESHOLD_DATE}\") | .id")
          
          for RUN_ID in $WORKFLOW_RUNS; do
            echo "Deleting workflow run with ID: $RUN_ID"
            curl -s -X DELETE -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID"
          done
