name: Run Python Script with Permissions Fixed

on:
 workflow_dispatch
jobs:
  run-python:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Fix permissions
      #   run: |
      #     sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Install Python and create virtual environment
        run: |
          # sudo apt update -y && \
          # sudo apt install -y python3 python3-venv && \
          python3 -m venv venv && \
          source venv/bin/activate && \
          pip install --upgrade pip && \
          pip install flask

      - name: Run Python Script
        run: |
          source venv/bin/activate && \
          python main.py
